services:

  app:
    image: my-app-front-dev
    build:
      context: ./frontend/ # The context will pick this directory as the "build context"
      dockerfile: ./dev.Dockerfile # This will simply tell which dockerfile to read
    environment:
      REACT_APP_BACKEND_URL: http://nginx:80
    volumes:
      - ./frontend/:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    container_name: my-app-front-dev # This will name the container

  server:
    image: my-app-back-dev
    build:
      context: ./backend/ # The context will pick this directory as the "build context"
      dockerfile: ./dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./backend/:/usr/src/app
    container_name: my-app-back-dev
    environment:
      - MONGO_URI=${MONGO_URI}
      - SECRET=${SECRET}
      - PORT=3000
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: my-app-reverse-proxy-dev
    depends_on:
      - app # wait for the frontend container to be started
